### ISSUE TITLE
克隆项目运行报错

### ISSUE THREAD

**Issue by Zhazhanan** [chenlei2/spring-boot-mybatis-rw#8]
最近在看springboot mybatis 数据读写分离，想研究下作者的代码。
### 有两个问题
- 项目spring-boot-mybatis-rw-sample与项目mybatis-rw-sample-xml都是测试项目吗
- 克隆项目跑起来报错
![1502176736 1](https://user-images.githubusercontent.com/17845256/29060731-9cc3010a-7c4d-11e7-8a35-8583f03a5eb3.jpg)
![1502176761 1](https://user-images.githubusercontent.com/17845256/29060737-a2d22f30-7c4d-11e7-8d4e-5b5c922a7e7a.jpg)
![1502176778 1](https://user-images.githubusercontent.com/17845256/29060745-a6a74ea6-7c4d-11e7-833b-68f194bf5f9c.jpg)

**Comment by chenlei2** [comment]
spring-boot-mybatis-rw-sample这个是springboot 启动的例子，mybatis-rw-sample-xml　是普通xml启动的例子，你启动报错，你用的idea是吧

**Comment by Zhazhanan** [comment]
是的，编译项目没有问题，启动项目spring-boot-mybatis-rw-sample报错，strudentsServiceImpl自动导入失败，说是未发现类RoundRobinRWRoutingDataSourceProxy

**Comment by chenlei2** [comment]
pom.xml 里面　把　    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>
    </build>
这个添加上

**Comment by chenlei2** [comment]
<build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>
    </build>

**Comment by chenlei2** [comment]
pom.xml把这个添加上

**Comment by chenlei2** [comment]
mybatis-rw-sample-xml　这个项目没维护了，启动不起来，你看spring-boot-mybatis-rw-sample　这个例子

**Comment by Zhazhanan** [comment]
可以了，项目跑起来了，我整理下问题，稍后拉取代码请求

- mybatis-rw-sample-xml项目启动报错如上截图，目前没有维护，所以不能启动
- spring-boot-mybatis-rw-sample项目 启动报错，原因：1、主要是java编译版本默认1.5 2、项目编译时没有加载mybatis的**.xml文件 3、默认数据库没有数据所以查询报错
